# Generated by Django 4.2.3 on 2023-07-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("الخدام", "0002_rename_الصورة_الخدام_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="الخدام",
            old_name="image",
            new_name="الصورة",
        ),
    ]
