# Generated by Django 4.2.3 on 2023-08-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("الخدام", "0003_rename_image_الخدام_الصورة"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="الخدام",
            name="العنوان",
        ),
        migrations.RemoveField(
            model_name="الخدام",
            name="القسم",
        ),
    ]
