# Generated by Django 4.2.3 on 2023-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("الاسم", models.CharField(max_length=50)),
                ("photo", models.FileField(upload_to="media/")),
                ("tel", models.TextField()),
                ("data", models.DateField()),
                ("gender", models.TextField()),
                ("Аddress", models.TextField()),
                ("mark", models.TextField()),
                ("degree", models.TextField()),
                ("الدفع", models.CharField(max_length=50)),
            ],
        ),
    ]
