# Generated by Django 4.2.3 on 2023-07-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="header",
            new_name="foot",
        ),
    ]
