# Generated by Django 4.2.2 on 2023-06-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark_sub", models.CharField(max_length=50)),
                ("mark_title", models.CharField(max_length=50)),
            ],
        ),
    ]
