# Generated by Django 4.2.2 on 2023-06-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mark", "0003_alter_mark_mark_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="mark",
            name="mark_image",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="header/"
            ),
        ),
    ]
