# Generated by Django 4.2.3 on 2023-07-20 06:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="الاجبية1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("واصف1", ckeditor.fields.RichTextField()),
                (
                    "صورة1",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
                ("عنوان1", ckeditor.fields.RichTextField()),
                ("واصف2", ckeditor.fields.RichTextField()),
                ("عنوان2", ckeditor.fields.RichTextField()),
                (
                    "صورة2",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
                ("واصف3", ckeditor.fields.RichTextField()),
                ("عنوان3", ckeditor.fields.RichTextField()),
                (
                    "صورة3",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية11",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية12",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية13",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("واصف1", ckeditor.fields.RichTextField()),
                (
                    "صورة1",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
                ("عنوان1", ckeditor.fields.RichTextField()),
                ("واصف2", ckeditor.fields.RichTextField()),
                ("عنوان2", ckeditor.fields.RichTextField()),
                (
                    "صورة2",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
                ("واصف3", ckeditor.fields.RichTextField()),
                ("عنوان3", ckeditor.fields.RichTextField()),
                (
                    "صورة3",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية21",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية22",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية23",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("واصف1", ckeditor.fields.RichTextField()),
                (
                    "صورة1",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
                ("عنوان1", ckeditor.fields.RichTextField()),
                ("واصف2", ckeditor.fields.RichTextField()),
                ("عنوان2", ckeditor.fields.RichTextField()),
                (
                    "صورة2",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
                ("واصف3", ckeditor.fields.RichTextField()),
                ("عنوان3", ckeditor.fields.RichTextField()),
                (
                    "صورة3",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية31",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية32",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
        migrations.CreateModel(
            name="الاجبية33",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("العنوان", ckeditor.fields.RichTextField()),
                ("الواصف", ckeditor.fields.RichTextField()),
                ("pdf", models.FileField(upload_to="header/")),
                ("audios", models.FileField(upload_to="header/")),
            ],
        ),
    ]
