# Generated by Django 4.2.3 on 2023-09-14 07:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="الصور",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("القسم", models.CharField(max_length=50)),
                ("العنوان", models.CharField(max_length=50)),
                ("الكلمة", ckeditor.fields.RichTextField()),
                ("عدد", models.CharField(max_length=50)),
                ("التاريخ", models.DateField()),
                ("المناسبة", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="الصورة",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("الصورة", models.ImageField(blank=True, upload_to="images/")),
                (
                    "الصور",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="الصور_الصورة",
                        to="photo.الصور",
                    ),
                ),
            ],
        ),
    ]
