# Generated by Django 4.2.3 on 2023-09-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="الصور",
            name="العنوان",
        ),
        migrations.RemoveField(
            model_name="الصور",
            name="القسم",
        ),
    ]
