# Generated by Django 4.2.3 on 2023-07-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("الخدام", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="الخدام",
            old_name="الصورة",
            new_name="image",
        ),
    ]
