# Generated by Django 4.2.3 on 2023-09-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_students_а"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="Аddress",
        ),
    ]
