# Generated by Django 4.2.3 on 2023-09-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_а_students_аddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="Аddress",
            new_name="العنوان",
        ),
    ]
