# Generated by Django 4.2.3 on 2023-07-19 19:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="new",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("القسم", models.CharField(max_length=50)),
                ("العنوان", models.CharField(max_length=50)),
                ("الواصف", ckeditor.fields.RichTextField()),
                (
                    "الصورة",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
            ],
        ),
    ]
