# Generated by Django 4.2.3 on 2023-07-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foot", "0003_rename_foot_انكل"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="انكل",
            new_name="foot",
        ),
    ]
