# Generated by Django 4.2.3 on 2023-07-13 21:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foot", "0005_alter_foot_foot_sub_alter_foot_foot_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foot",
            name="foot_sub",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="foot",
            name="foot_title",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
