# Generated by Django 4.2.2 on 2023-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mark", "0002_alter_mark_mark_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="mark_title",
            field=models.CharField(max_length=200),
        ),
    ]
