# Generated by Django 4.2.3 on 2023-09-14 09:29

from django.db import migrations, models
import mark.models


class Migration(migrations.Migration):

    dependencies = [
        ("mark", "0004_mark_mark_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mark_image",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to=mark.models.get_upload_path,
                    ),
                ),
            ],
        ),
    ]
