# Generated by Django 4.2.2 on 2023-06-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_des2",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
