# Generated by Django 4.2.2 on 2023-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0003_header_header_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_image1",
            field=models.ImageField(default=1, upload_to="../static/assets/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="header",
            name="header_image2",
            field=models.ImageField(default=1, upload_to="../static/assets/"),
            preserve_default=False,
        ),
    ]
