# Generated by Django 4.2.2 on 2023-06-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0004_header_header_image1_header_header_image2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="header_image",
            field=models.ImageField(upload_to="assets/images/"),
        ),
        migrations.AlterField(
            model_name="header",
            name="header_image1",
            field=models.ImageField(upload_to="assets/images/"),
        ),
        migrations.AlterField(
            model_name="header",
            name="header_image2",
            field=models.ImageField(upload_to="assets/images/"),
        ),
    ]
