# Generated by Django 4.2.2 on 2023-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "header",
            "0005_alter_header_header_image_alter_header_header_image1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="header_image",
            field=models.ImageField(upload_to="heeder/static/c21/image/"),
        ),
        migrations.AlterField(
            model_name="header",
            name="header_image1",
            field=models.ImageField(upload_to="heeder/static/c21/image/"),
        ),
        migrations.AlterField(
            model_name="header",
            name="header_image2",
            field=models.ImageField(upload_to="heeder/static/c21/image/"),
        ),
    ]
