# Generated by Django 4.2.2 on 2023-06-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0007_mark"),
    ]

    operations = [
        migrations.CreateModel(
            name="new",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_sub", models.CharField(max_length=50)),
                ("new_title", models.CharField(max_length=50)),
                ("new_des", models.TextField()),
            ],
        ),
    ]
