# Generated by Django 4.2.2 on 2023-06-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0009_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="day_title",
        ),
    ]
