# Generated by Django 4.2.2 on 2023-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0013_remove_header_header_image1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_image2",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="header/"
            ),
        ),
        migrations.AddField(
            model_name="header",
            name="header_image3",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="header/"
            ),
        ),
    ]
