# Generated by Django 4.2.2 on 2023-06-30 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0015_header_header_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="header_pdf",
            field=models.FileField(
                blank=True,
                max_length=1000,
                null=True,
                upload_to="header/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
