# Generated by Django 4.2.2 on 2023-06-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0018_alter_header_header_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="header",
            name="header_pdf",
        ),
    ]
