# Generated by Django 4.2.2 on 2023-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0019_remove_header_header_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_pdf",
            field=models.FileField(default=2, upload_to="header/"),
            preserve_default=False,
        ),
    ]
