# Generated by Django 4.2.2 on 2023-06-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0020_header_header_pdf"),
    ]

    operations = [
        migrations.DeleteModel(
            name="new",
        ),
    ]
