# Generated by Django 4.2.2 on 2023-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0022_alter_header_header_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="header_pdf",
            field=models.FileField(default=2, upload_to="header/"),
            preserve_default=False,
        ),
    ]
