# Generated by Django 4.2.2 on 2023-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0023_alter_header_header_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="header_pdf",
            field=models.FileField(blank=True, null=True, upload_to="header/"),
        ),
    ]
