# Generated by Django 4.2.2 on 2023-07-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0024_alter_header_header_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="header",
            old_name="header_pdf",
            new_name="header_pr",
        ),
    ]
