# Generated by Django 4.2.3 on 2023-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0027_alter_header_header_des"),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="header_des",
            field=models.TextField(),
        ),
    ]
