# Generated by Django 4.2.2 on 2023-06-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0002_header_header_des2"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_image",
            field=models.ImageField(default=1, upload_to="../static/assets/"),
            preserve_default=False,
        ),
    ]
