# Generated by Django 4.2.2 on 2023-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "header",
            "0006_alter_header_header_image_alter_header_header_image1_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark_sub", models.CharField(max_length=50)),
                ("mark_title", models.CharField(max_length=50)),
            ],
        ),
    ]
