# Generated by Django 4.2.2 on 2023-06-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0011_delete_mark"),
    ]

    operations = [
        migrations.DeleteModel(
            name="day",
        ),
    ]
