# Generated by Django 4.2.2 on 2023-06-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0014_header_header_image2_header_header_image3"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_pdf",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="header/"
            ),
        ),
    ]
