# Generated by Django 4.2.2 on 2023-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0025_rename_header_pdf_header_header_pr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="header_pr",
            field=models.FileField(default=2, upload_to="header/"),
            preserve_default=False,
        ),
    ]
