# Generated by Django 4.2.3 on 2023-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "photo",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="header/"
                    ),
                ),
                ("tel", models.TextField()),
                ("data", models.DateField()),
                ("gender", models.TextField()),
                ("Addres", models.TextField()),
                ("mark", models.TextField()),
                ("degree", models.TextField()),
            ],
        ),
    ]
