# Generated by Django 4.2.3 on 2023-07-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Abram",
            new_name="Student",
        ),
    ]
