# Generated by Django 4.2.3 on 2023-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0002_rename_abram_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="media/"
            ),
        ),
    ]
