# Generated by Django 4.2.3 on 2023-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0003_alter_student_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Addres",
            new_name="Address",
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                default=None, max_length=250, null=True, upload_to="photos/"
            ),
        ),
    ]
