# Generated by Django 4.2.3 on 2023-07-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0004_rename_addres_student_address_alter_student_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Address",
            new_name="Addres",
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="header/"
            ),
        ),
    ]
