# Generated by Django 4.2.3 on 2023-07-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0006_alter_student_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="الاسم",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="data",
            new_name="التاريخ",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="Addres",
            new_name="الجنس",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="degree",
            new_name="العنوان",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="gender",
            new_name="المرحلة",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="mark",
            new_name="الهاتف",
        ),
        migrations.RemoveField(
            model_name="student",
            name="tel",
        ),
    ]
