# Generated by Django 4.2.3 on 2023-07-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0007_rename_name_student_الاسم_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="الجنس",
            new_name="Addres",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="التاريخ",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="العنوان",
            new_name="degree",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="المرحلة",
            new_name="gender",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="الهاتف",
            new_name="mark",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="الاسم",
            new_name="name",
        ),
        migrations.AddField(
            model_name="student",
            name="tel",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
