# Generated by Django 4.2.3 on 2023-07-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0008_rename_الجنس_student_addres_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="الاسم",
        ),
    ]
