# Generated by Django 4.2.3 on 2023-07-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0009_rename_name_student_الاسم"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="الدفع",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
