# Generated by Django 4.2.3 on 2023-09-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0011_formconfiguration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formconfiguration",
            old_name="allowed",
            new_name="is_open",
        ),
        migrations.RemoveField(
            model_name="formconfiguration",
            name="student",
        ),
    ]
