# Generated by Django 4.2.3 on 2023-09-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new2", "0012_rename_allowed_formconfiguration_is_open_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Addres",
            new_name="Аddress",
        ),
    ]
